### ISSUE TITLE
Unable to see log statement in a CF console

### ISSUE THREAD

**Issue by antonevane** [cloudfoundry-community/cf-helper-php#1]
Hi, I have an app that is using logger from helper:

```
<?php
    // set up Composer autoloader
    require 'vendor/autoload.php';
    use CfCommunity\CfHelper\CfHelper;
    $logger = CfHelper::getInstance()->getLogger();
    ...........
    $logger->addInfo('###########################################');
    $logger->addInfo('LOG OCCURED');
    $logger->addInfo('###########################################');
?>
```

I don't see any log statements.
     cf logs  <APP_NAME>

I'm using the following command.

**Comment by ArthurHlt** [comment]
I don't know why this was not working properly. So ok I fix this issue, thanks for the post. 
You can use the new release [1.5.1](https://github.com/cloudfoundry-community/cf-helper-php/releases/tag/1.5.1)

**Comment by ArthurHlt** [comment]
see commit here: https://github.com/cloudfoundry-community/cf-helper-php/commit/47a772d871f699d213ea6141173b0a1133fca446

**Comment by antonevane** [comment]
Thanks
