### ISSUE TITLE
Add ability to override Logger behaviour

### ISSUE THREAD

**Issue by antonevane** [cloudfoundry-community/cf-helper-php#2]
Hi,
 Can you to add new API Method to set Logger name.

```
[App/0]      OUT 19:40:30 nginx   | PHP message: [2015-06-23 19:40:30] CloudFoundry Helper.INFO: Service started process a request [] []
```

And Is there a way to not include the following 'PHP message:' in the message and the brackets.

Monolog handlers:
http://stackoverflow.com/questions/13968967/how-not-to-show-last-bracket-in-a-monolog-log-line

**Comment by ArthurHlt** [comment]
`PHP messages` doesn't come from monolog for sure, I think it comes from php buildpack or php-fpm output (not sure). 
Anyway, if you want to format the rest of the line you can set a [Monolog Formatter](https://github.com/Seldaek/monolog/blob/master/doc/02-handlers-formatters-processors.md#formatters) like this for example:

``` php
<?php
$formatter = new LineFormatter(null, null, false, true);
CfHelper::getInstance()->getLogger()->getCloudFoundryHandler()->setFormatter($formatter);
```

**Comment by antonevane** [comment]
Thanks again. Php is pretty new for me (it's my the first week).

**Comment by ArthurHlt** [comment]
Thanks to you. Well it will be hard for you to know all about this things.
