### ISSUE TITLE
Including 1.6.2 in latest Cachet

### ISSUE THREAD

**Issue by fdhex** [cloudfoundry-community/cf-helper-php#4]
I seem to have an incompatibility using 1.6.2 with the latest version of the composer.json of Cachet.

The composer sometimes hangs indefinitely trying to include this repo (running composer update), sometimes fails on sphring inclusion. Have you had a try?

**Comment by ArthurHlt** [comment]
Hello @fdhex, 
Thank you for your report. 
It was a dependencies which was to tied to a version and was conflicting with laravel (framework that cachet use). 

I did the fix and i suppose you wanted to bump the version of Cachet-cf, I did it after this fix. You can find this release here: https://github.com/cloudfoundry-community/Cachet-cf/releases/tag/v2.3.10-cf

I consider this as closed, feel free to tell me if it must remains open
